[package]
name = "margen"
version = "0.1.0"
authors = ["Nuew <code@nuew.net>"]
description = "A user-configurable mathematical image generator"

[dependencies]
env_logger = "0.3"
hlua = "0.1"
image = "0.10"
log = "0.3"
